/**
 * Video Generation Tool for Veo 3.1
 * Supports Text-to-Video, Image-to-Video, and Reference Images
 */

import {
  GEMINI_API_BASE_URL,
  DEFAULT_MODEL,
  DEFAULT_RESOLUTION,
  DEFAULT_ASPECT_RATIO,
  DEFAULT_DURATION,
  DEFAULT_POLL_INTERVAL,
  DEFAULT_MAX_POLL_ATTEMPTS,
  normalizeModel,
  normalizeResolution,
  normalizeAspectRatio,
  normalizeDuration,
  calculateCost,
  isValidResolutionForModel,
  type GenerateVideoParams,
  type VeoGenerateRequest,
  type VeoOperationResponse,
  type VideoGenerationResult,
  type Model,
  type Resolution
} from '../types/tools.js';
import {
  getApiKey,
  pollVideoResult,
  downloadAndSaveVideo,
  extractVideosFromResponse,
  readImageWithMimeType
} from '../utils/video.js';
import { generateDefaultOutputPath, getDisplayPath } from '../utils/path.js';
import { debugLog, errorLog } from '../utils/debug.js';

/**
 * Generate a video using Veo 3.1 API
 */
export async function generateVideo(params: GenerateVideoParams): Promise<VideoGenerationResult> {
  const apiKey = getApiKey();

  // Normalize parameters (invalid values are rejected rather than
  // silently replaced, since generation is billed)
  let model: Model;
  let resolution: Resolution;
  let aspectRatio: string;
  let durationSeconds: number;
  try {
    model = normalizeModel(params.model);
    resolution = normalizeResolution(params.resolution);
    aspectRatio = normalizeAspectRatio(params.aspect_ratio);
    durationSeconds = normalizeDuration(params.duration_seconds);
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error)
    };
  }
  const generateAudio = params.generate_audio ?? true;
  const sampleCount = typeof params.sample_count === 'string'
    ? parseInt(params.sample_count, 10)
    : (params.sample_count ?? 1);

  // Validate resolution for model
  if (!isValidResolutionForModel(resolution, model)) {
    return {
      success: false,
      error: `Resolution ${resolution} is not available for model ${model}. Fast model only supports 720p and 1080p.`
    };
  }

  // Validate prompt
  if (!params.prompt && !params.image) {
    return {
      success: false,
      error: 'Either prompt or image is required for video generation'
    };
  }

  debugLog('Generating video with parameters', {
    model,
    resolution,
    aspectRatio,
    durationSeconds,
    generateAudio,
    hasImage: !!params.image,
    hasReferenceImages: !!params.reference_images?.length
  });

  try {
    // Build request instance
    const instance: VeoGenerateRequest['instances'][0] = {};

    if (params.prompt) {
      instance.prompt = params.prompt;
    }

    // Handle input image (Image-to-Video)
    if (params.image) {
      if (params.image.startsWith('gs://')) {
        instance.image = { gcsUri: params.image };
      } else {
        const imageData = await readImageWithMimeType(params.image);
        instance.image = {
          bytesBase64Encoded: imageData.base64,
          mimeType: imageData.mimeType
        };
      }
    }

    // Handle reference images
    if (params.reference_images && params.reference_images.length > 0) {
      instance.referenceImages = [];

      for (const refImage of params.reference_images) {
        let imageInput;
        if (refImage.image.startsWith('gs://')) {
          imageInput = { gcsUri: refImage.image };
        } else {
          const imageData = await readImageWithMimeType(refImage.image);
          imageInput = {
            bytesBase64Encoded: imageData.base64,
            mimeType: imageData.mimeType
          };
        }

        instance.referenceImages.push({
          image: imageInput,
          referenceType: refImage.reference_type
        });
      }
    }

    // Build request parameters
    // Note: generateAudio is NOT supported in Gemini API preview models
    // Audio is always generated by default in Veo 3.1 preview
    const requestParams: VeoGenerateRequest['parameters'] = {
      aspectRatio,
      resolution,
      durationSeconds,
      sampleCount
    };

    if (params.negative_prompt) {
      requestParams.negativePrompt = params.negative_prompt;
    }

    if (params.person_generation) {
      requestParams.personGeneration = params.person_generation;
    }

    if (params.seed !== undefined) {
      requestParams.seed = typeof params.seed === 'string'
        ? parseInt(params.seed, 10)
        : params.seed;
    }

    if (params.compression_quality) {
      requestParams.compressionQuality = params.compression_quality;
    }

    if (params.resize_mode) {
      requestParams.resizeMode = params.resize_mode;
    }

    if (params.storage_uri) {
      requestParams.storageUri = params.storage_uri;
    }

    // Build full request
    const request: VeoGenerateRequest = {
      instances: [instance],
      parameters: requestParams
    };

    debugLog('API Request', request);

    // Make API call
    const url = `${GEMINI_API_BASE_URL}/models/${model}:predictLongRunning`;

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-goog-api-key': apiKey
      },
      body: JSON.stringify(request)
    });

    if (!response.ok) {
      const errorText = await response.text();
      errorLog('API request failed', { status: response.status, error: errorText });

      // Handle specific error codes
      if (response.status === 401) {
        return {
          success: false,
          error: 'Authentication failed. Please check your GOOGLE_API_KEY.'
        };
      }

      if (response.status === 403) {
        return {
          success: false,
          error: 'Access denied. Your API key may not have access to Veo 3.1.'
        };
      }

      if (response.status === 429) {
        return {
          success: false,
          error: 'Rate limit exceeded. Please try again later.'
        };
      }

      return {
        success: false,
        error: `API request failed: ${response.status} ${response.statusText} - ${errorText}`
      };
    }

    const operationResponse = await response.json() as VeoOperationResponse;
    debugLog('Initial operation response', operationResponse);

    const operationName = operationResponse.name;

    // Calculate estimated cost
    const estimatedCost = calculateCost(model, resolution, durationSeconds, generateAudio);

    // Async mode: return immediately; the caller polls with get_video_status
    if (params.wait === false) {
      return {
        success: true,
        done: false,
        operation_name: operationName,
        duration_seconds: durationSeconds,
        estimated_cost: estimatedCost
      };
    }

    // Poll for completion
    const pollInterval = params.poll_interval
      || parseInt(process.env.VIDEO_POLL_INTERVAL || '') || DEFAULT_POLL_INTERVAL;
    const maxAttempts = parseInt(process.env.VIDEO_MAX_POLL_ATTEMPTS || '') || DEFAULT_MAX_POLL_ATTEMPTS;

    const finalResponse = await pollVideoResult(operationName, apiKey, pollInterval, maxAttempts);

    // Check for errors
    if (finalResponse.error) {
      return {
        success: false,
        operation_name: operationName,
        error: finalResponse.error.message,
        failure_reason: `Error code: ${finalResponse.error.code}`
      };
    }

    // Extract video data (may be multiple when sample_count > 1)
    const videos = extractVideosFromResponse(finalResponse);

    if (videos.length === 0) {
      return {
        success: false,
        operation_name: operationName,
        error: 'No video was generated. The content may have been filtered by safety policies.',
        estimated_cost: estimatedCost
      };
    }

    // Download and save if output path specified
    const videoPaths: string[] = [];

    if (params.output_path || process.env.OUTPUT_DIR) {
      const outputPath = params.output_path || generateDefaultOutputPath(
        process.env.OUTPUT_DIR || './output',
        'veo3'
      );

      for (const video of videos) {
        try {
          // saveVideo uniquifies the filename, so all samples share the same base path
          const savedPath = await downloadAndSaveVideo(video.url, video.base64, outputPath);
          videoPaths.push(savedPath);
          debugLog('Video saved', { path: savedPath });
        } catch (downloadError) {
          errorLog('Failed to save video', downloadError);
          // Don't fail the whole operation if download fails
        }
      }
    }

    const videoUrls = videos.map(v => v.url).filter((u): u is string => !!u);
    const displayPaths = videoPaths.map(p => getDisplayPath(p));

    return {
      success: true,
      done: true,
      operation_name: operationName,
      video_url: videoUrls[0],
      video_path: displayPaths[0],
      video_urls: videoUrls.length > 1 ? videoUrls : undefined,
      video_paths: displayPaths.length > 1 ? displayPaths : undefined,
      duration_seconds: durationSeconds,
      estimated_cost: estimatedCost
    };

  } catch (error) {
    errorLog('Video generation failed', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error)
    };
  }
}
